### ISSUE TITLE
期望你能继续更新，谢谢！

### ISSUE THREAD

**Issue by 5iCruise** [HerbertChang/pmweekly#1]
无意中看到你的“产品周刊”栏目，做的很用心，期望你能继续用你的专业视角作出具有特色、小而美的个性内容。

**Comment by HerbertChang** [comment]
> 无意中看到你的“产品周刊”栏目，做的很用心，期望你能继续用你的专业视角作出具有特色、小而美的个性内容。

感谢支持，努力更新中~
